# NOTE
#
# For the includes to be executed in the correct order when they
# have dependencies there must be one include statement. The 'needs'
# keyword does not otherwise resolve a jobs in a different include
# file if it is in a different include block.
# I.e. I cannot do this:
#
# include:
#   - local: .gitlab/infrastructure.yml
#
# include:
#   - local: .gitlab/stage_clear_cache.yml
#
# Particularly if stage_clear_cache.yml contains jobs with the needs
# keyword that names a job in infrastructure.yml
include:
    - local: .gitlab/stage_pipeline_serialize.yml
    - local: .gitlab/infrastructure.yml
    - local: .gitlab/stage_clear_cache.yml
    - local: .gitlab/stage_build_base.yml
    - local: .gitlab/stage_test.yml

stages:
    - pipeline-serialize
    - ci-infrastructure-check
    - trigger-infrastructure
    - signal
    - clear-docker-cache
    - build-base
    - test # Required for gitlab sast templates

# WARNING
#
# Do not put if else statements without if and else, gitlab yaml does not like
# this kind of scripting
#
# [ -f file_path ] && ok do this....
variables:
    HARBOR_USER: "robot$$datafed+harbor_datafed_gitlab_ci_registry_2"
    REGISTRY: "camden.ornl.gov"
    DATAFED_DEPENDENCIES_INSTALL_PATH: "/shared/install"
    DOCKER_TLS_CERTDIR: "" # Required for running docker in docker
